### ISSUE TITLE
[Discussion] Rename this repository to GuardianConnector Explorer (or other)

### ISSUE THREAD

**Issue by rudokemper** [ConservationMetrics/guardianconnector-views#78]
This is not urgent.

When I started this repository and when it was donned "Views", it was just a super basic Express app serving .EJS templates (https://github.com/ConservationMetrics/guardianconnector-views/commit/663c93cebc8d72e2e489f1e7d3baa0bac05f8793). At the time, the envisioned scope of this repo was just to provide some supplementary views of data that Superset was not able to provide -- like a better Mapbox map than Superset's own limited map chart, and a gallery view of images. 

Since then, I’ve transformed it into a full-stack Nuxt.js application, which we’ve used to create much more complex 'views' with filtering and other functionality, such as the alerts feature. In the next phase of work, we are considering adding behaviors like attaching metadata to alerts, which would require writing to the database in addition to reading. In other words, we are enabling users to do much more with their data than simply 'viewing'.

Consequently, I propose a rename. What comes to my mind is "Explorer." The term suggests the ability to answer more complex data queries—which we’re already doing in the alerts view to some extent by providing statistics—and also implies the capability to modify data, much like you can with files in Windows Explorer. But open to other suggestions.

_As an aside, it's a bit confusing that Vue is pronounced " /vjuː/", like view._

**Comment by IamJeffG** [comment]
No objections. I think "Explorer" is a great name.  One nuance that occurs to me is Superset is largely tabular whereas Views is largely pictures (whether maps or photos)--although that's also an oversimplification--so I wonder if there exists a name that captures that nuance.  But "Explorer" is great.

I'd suggest this issue needs to address (even if not fully solve):
- Git repository name , as you have
- Does the Docker image name change?  This would require bumping the string on existing deployments.
- Does the subdomain change for new deployments? for old deployments too?  This would require changes in gc-force and auth0.

**Comment by rudokemper** [comment]
Thanks Jeff. That's an interesting observation that has me thinking about names that allude to vision, like Vista or Panorama... these are perhaps too metaphorical, though, and get us back to the problem of connoting a behavior of  "only" viewing.
